name: Python application CI

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Récupère les sources du dépôt dans le conteneur
      - uses: actions/checkout@v4

      # On configure python dans le conteneur
      - uses: actions/setup-python@v5
        # On sélectionne la version de python souhaitée
        with:
          python-version: '3.10'
      # Exécution des tests de notre programme
      - run: python -m unittest test_addition.py
